### ISSUE TITLE
conftest.py discovery when running pytest --rootdir

### ISSUE THREAD

**Issue by piotr-kubiak** [pytest-dev/pytest#11071]
My setup:
```
(.venv) [root@4bd7686ed675 git_root]# pwd
/root/git_root
(.venv) [root@4bd7686ed675 git_root]# tree
.
├── important_folder
├── other_folder
└── package_root
    ├── conftest.py
    ├── src
    │   └── my_package
    │       ├── __init__.py
    │       └── main.py
    └── tests
        ├── __init__.py
        └── test_main.py

(.venv) [root@4bd7686ed675 git_root]# pip list
Package        Version
-------------- -------
exceptiongroup 1.1.1
iniconfig      2.0.0
packaging      23.1
pip            21.2.3
pluggy         1.0.0
pytest         7.3.1
setuptools     53.0.0
tomli          2.0.1
```
The contents of `conftest.py`:
```
(.venv) [root@4bd7686ed675 git_root]# cat package_root/conftest.py 
pytest_plugins = ""
```
All other files are empty.
Let's run `pytest`:
```
(.venv) [root@4bd7686ed675 git_root]# pytest
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /root/git_root
collected 0 items / 1 error                                                                                                                                                     

==================================================================================== ERRORS =====================================================================================
_________________________________________________________________________ ERROR collecting test session _________________________________________________________________________
Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
It affects the entire test suite instead of just below the conftest as expected.
  /root/git_root/package_root/conftest.py
Please move it to a top level conftest file at the rootdir:
  None
For more information, visit:
  https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files
============================================================================ short test summary info ============================================================================
ERROR 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 1 error in 0.09s ================================================================================
```
Ok, that is an error, because `conftest.py` is not in `rootdir: /root/git_root`. Let's try to fix it:
```
(.venv) [root@4bd7686ed675 git_root]# pytest --rootdir=/root/git_root/package_root/
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /root/git_root/package_root
collected 0 items                                                                                                                                                               
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/main.py", line 646, in perform_collect
INTERNALERROR>     rep = collect_one_node(self)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/runner.py", line 545, in collect_one_node
INTERNALERROR>     ihook = collector.ihook
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/nodes.py", line 267, in ihook
INTERNALERROR>     return self.session.gethookproxy(self.path)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/main.py", line 542, in gethookproxy
INTERNALERROR>     my_conftestmodules = pm._getconftestmodules(
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 602, in _getconftestmodules
INTERNALERROR>     mod = self._importconftest(conftestpath, importmode, rootpath)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 640, in _importconftest
INTERNALERROR>     self._check_non_top_pytest_plugins(mod, conftestpath)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 672, in _check_non_top_pytest_plugins
INTERNALERROR>     fail(msg.format(conftestpath, self._confcutdir), pytrace=False)
INTERNALERROR>   File "/root/git_root/.venv/lib64/python3.9/site-packages/_pytest/outcomes.py", line 198, in fail
INTERNALERROR>     raise Failed(msg=reason, pytrace=pytrace)
INTERNALERROR> Failed: Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
INTERNALERROR> It affects the entire test suite instead of just below the conftest as expected.
INTERNALERROR>   /root/git_root/package_root/conftest.py
INTERNALERROR> Please move it to a top level conftest file at the rootdir:
INTERNALERROR>   None
INTERNALERROR> For more information, visit:
INTERNALERROR>   https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files
```
Unfortunately, still an error, which seems like a bug to me, because now `conftest.py` **is** in the `rootdir`.
Let's change current dir and try again:
```
(.venv) [root@4bd7686ed675 git_root]# cd package_root/
(.venv) [root@4bd7686ed675 package_root]# pytest --rootdir=/root/git_root/package_root/
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /root/git_root/package_root
collected 0 items                                                                                                                                                               

============================================================================= no tests ran in 0.01s =============================================================================
```
I suppose that the output of `pytest --rootdir=<dir>` should not be dependent on current working directory.

Some background:
While working from `package_root/` seems like a workaround, this is not convenient enough for me. My company requires me to put some PM-related stuff inside our git repositories (`important_folder/`). We are then using VS Code to open `git_root/` as a workspace, and work from there.

**Comment by bluetech** [comment]
This looks buggy. Unfortunately I don't have time for a full analysis, but one thing for sure is that the message "Please move it to a top level conftest file at the rootdir" is not accurate as written. The actual logic is described [here](https://docs.pytest.org/en/latest/how-to/writing_plugins.html#plugin-discovery-order-at-tool-startup) and implemented [here](https://github.com/pytest-dev/pytest/blob/6c9b277ce4fc87886a13e29184c278bdbbb5386b/src/_pytest/config/__init__.py#L528-L569).

If you just want to get it working for now, you can add a pytest.ini with `testpaths`, e.g.

```ini
# /root/git_root/pytest.ini
[pytest]
testpaths = package_root
```

You can add other paths there of course if you have them. You don't need to set `rootdir`.

**Comment by bluetech** [comment]
BTW the `None` line is fixed by 4a1bba25b9ad23dccc00c695ffb4050b6ddb4189 though it does not affect this issue otherwise.

**Comment by piotr-kubiak** [comment]
@bluetech Thanks for the tips. I did some investigation, maybe that helps.

I did try newest main version, and indeed the message looks better:
```
INTERNALERROR> It affects the entire test suite instead of just below the conftest as expected.
INTERNALERROR>   /root/git_root/package_root/conftest.py
INTERNALERROR> Please move it to a top level conftest file at the rootdir:
INTERNALERROR>   /root/git_root/package_root
```
However, now it asks me to move the file effectively to the same location.
So I dig deeper.
I've ran `git bisect`, and managed to find the commit that introduced the 'bug': a93f412, however that is exactly the same commit where that warning was introduced so that does not help.
So I dig deeper.

I've found that the logic to show the warning is just three conditions:
```python
hasattr(mod, "pytest_plugins")
and self._configured
and not self._using_pyargs
```
The first one is `True` since that is the contents of my `conftest.py`, the third one resolves to `True` since I am not using pyargs. So I am left with the second one. 

There seems to be somehow implied logic there: you are not checking if the `conftest.py` is in the proper directory as the warning message says, but instead you are checking if the import happened when `_configured=False`, i.e before the configure stage. If it happens later, it is implied that the directory is not top-level.

So the real question is: why in my example the import doesn't happen in the configure stage.

**Comment by bluetech** [comment]
The error message is not accurate. The initial conftests are not searched in the rootdir, they are searched in the `testpaths` (configured in pytest.ini), the command line arguments (e.g. `pytest foo/`), and if not found, in the current directory. The conftest in your example is not in any of those, so it is not considered an initial conftest.

So either the logic or the message should be fixed, I'm not sure which ATM.

**Comment by Yao-T** [comment]
> @bluetech Thanks for the tips. I did some investigation, maybe that helps.
> 
> I did try newest main version, and indeed the message looks better:
> 
> ```
> INTERNALERROR> It affects the entire test suite instead of just below the conftest as expected.
> INTERNALERROR>   /root/git_root/package_root/conftest.py
> INTERNALERROR> Please move it to a top level conftest file at the rootdir:
> INTERNALERROR>   /root/git_root/package_root
> ```
> 
> However, now it asks me to move the file effectively to the same location. So I dig deeper. I've ran `git bisect`, and managed to find the commit that introduced the 'bug': [a93f412](https://github.com/pytest-dev/pytest/commit/a93f41233a8f4edadb33a055396247ef1ede210a), however that is exactly the same commit where that warning was introduced so that does not help. So I dig deeper.
> 
> I've found that the logic to show the warning is just three conditions:
> 
> ```python
> hasattr(mod, "pytest_plugins")
> and self._configured
> and not self._using_pyargs
> ```
> 
> The first one is `True` since that is the contents of my `conftest.py`, the third one resolves to `True` since I am not using pyargs. So I am left with the second one.
> 
> There seems to be somehow implied logic there: you are not checking if the `conftest.py` is in the proper directory as the warning message says, but instead you are checking if the import happened when `_configured=False`, i.e before the configure stage. If it happens later, it is implied that the directory is not top-level.
> 
> So the real question is: why in my example the import doesn't happen in the configure stage.

maybe my solution can help you. I think it is not matter whether you have your `conftest.py` or your plugins  in your root directory. What is important to define your own `entry` of your own project. The plugins can be called in your own project.

Here is my project structure

![image](https://github.com/pytest-dev/pytest/assets/33818798/a5ecaea2-72f3-48cf-b5cd-86a4d6cf0dee)

Add your project to the `PYTHONPATH`. I had my own `export.sh`

![image](https://github.com/pytest-dev/pytest/assets/33818798/95f02c50-60aa-4aed-b9be-c483ba1c4728)


Here is my `conftest.py`. 

![image](https://github.com/pytest-dev/pytest/assets/33818798/436f46dd-d5bb-49b6-95d4-682c94b814e4)


Hope this will help you!

**Comment by piotr-kubiak** [comment]
Error is still there, however the message slighlty changed.
It now basically says I need to move conftest.py to the folder where it already is.

```
  H:\python\pytest-root\package_root\conftest.py
Please move it to a top level conftest file at the rootdir:
  H:\python\pytest-root\package_root
```

<details>

```
$ pytest --rootdir h:\\python\\pytest-root\\package_root\\
=================================================================================================================================== test session starts ====================================================================================================================================
platform win32 -- Python 3.11.7, pytest-8.3.2, pluggy-1.5.0
rootdir: H:\python\pytest-root\package_root
plugins: django-4.9.0, xdist-3.6.1
collected 0 items / 1 error                                                                                                                                                                                                                                                                  

========================================================================================================================================== ERRORS ========================================================================================================================================== 
____________________________________________________________________________________________________________________________________ ERROR collecting . ____________________________________________________________________________________________________________________________________ 
Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
It affects the entire test suite instead of just below the conftest as expected.
  H:\python\pytest-root\package_root\conftest.py
Please move it to a top level conftest file at the rootdir:
  H:\python\pytest-root\package_root
For more information, visit:
  https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files
================================================================================================================================= short test summary info ================================================================================================================================== 
ERROR package_root - Failed: Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
===================================================================================================================================== 1 error in 0.29s =====================================================================================================================================
```
</details>
