### ISSUE TITLE
reruns not captured to html report when both --rerun and -n options used together

### ISSUE THREAD

**Issue by cauveryguda** [pytest-dev/pytest#2837]
The reruns are not being captured to html report when both --reruns and -n options are used in the same command line

For example my command line looks like;
pytest --rerun 1 -n 3 --html=reporthtml/report.html --junitxml=report/report.xml -s tests/<mytest>

When -n 3 is  removed, then the reruns are captured to html report. 

The Versions I am using:
pytest (3.1.3)
pytest-html (1.15.1)
pytest-rerunfailures (2.2)

The screenshot shows the reruns captured in html report. Please let me know if any more details are needed.

Thank you.
![screen shot 2017-10-13 at 11 51 27 am](https://user-images.githubusercontent.com/12631004/31561506-eb427e12-b00c-11e7-8eb7-174455659cbb.png)

**Comment by nicoddemus** [comment]
@cauveryguda this has been fixed in [pytest-xdist 1.20.0](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst#pytest-xdist-1200-2017-08-17), which version are you using?

(The `-n` option is not native to pytest, is from the `pytest-xdist` plugin)

**Comment by cauveryguda** [comment]
Thank you for your response.
I am using pytest-xdist-1.18.0.  I will update and see if it helps. 

-Cauvery

**Comment by nicoddemus** [comment]
No worries. Please come back with your findings.

**Comment by cauveryguda** [comment]
Hi Nicoddemus, 

I upgraded to pytest-xdist-1.20.1  but still having the same issue of reruns not captured in html reports. 
Here are the full details of what I versions I have 
  pytest-xdist-1.20.1 at /usr/local/lib/python2.7/site-packages/xdist/looponfail.py
  pytest-xdist-1.20.1 at /usr/local/lib/python2.7/site-packages/xdist/plugin.py
  pytest-rerunfailures-2.2 at /usr/local/lib/python2.7/site-packages/pytest_rerunfailures.py
  pytest-progress-1.0.2 at /usr/local/lib/python2.7/site-packages/pytest_progress.py
  pytest-metadata-1.5.0 at /usr/local/lib/python2.7/site-packages/pytest_metadata/plugin.py
  pytest-html-1.15.1 at /usr/local/lib/python2.7/site-packages/pytest_html/plugin.py
  pytest-forked-0.2 at /usr/local/lib/python2.7/site-packages/pytest_forked/__init__.pyc

Here is the command line I tried  (both --rerun  an d --reruns)  
pytest --reruns 2 -n 3 --html reporthtml/report.html tests/<testfolder>

pytest --rerun 2 -n 3 --html reporthtml/report.html tests/<testfolder>

and just fyi, I can see the tests failed (purposefully failed) and they are being rerun. But when the -n option is removed then the reruns is captured in html reports. 

Thanks,
Cauvery.

**Comment by nicoddemus** [comment]
@davehunt do you have any thoughts here?

**Comment by davehunt** [comment]
I believe pytest-rerunfailures 3.1 is required.

**Comment by cauveryguda** [comment]
Hi @davehunt, 

Upgraded pytest-rerunfailures to 3.1 and now it is working as expected. Thank you for the help.
