### ISSUE TITLE
Testing argparse accepting strings from stdin raises OSError

### ISSUE THREAD

**Issue by DahlitzFlorian** [pytest-dev/pytest#7284]
- [X] a detailed description of the bug or suggestion

I was working on an enhancement of the `astpretty` module, which eventually should support piping strings into it like `echo "x = y" | astpretty`. However, if testing the approach I used to implement this feature, `pytest` raises an OSError.

- [X] minimal example if possible

```shell
$ tree .
.
├── test
│   └── test_main.py
└── t.py

1 directory, 2 files
```

```python
# t.py
import sys
from argparse import ArgumentParser


def main(argv=None):
    parser = ArgumentParser()
    parser.add_argument('filename', nargs='?')
    args = parser.parse_args(argv)

    if args.filename:
        with open(args.filename, 'rb') as f:
            contents = f.read()
    elif not sys.stdin.isatty():
        contents = sys.stdin.read().encode('utf-8')
    else:
        parser.print_help()
        return 0

    print("Finished")
    return 0


if __name__ == "__main__":
    exit(main())
```

```python
# test/test_main.py
import t


def test_main(capsys, tmpdir):
    expected = '''\
usage: t.py [-h] [filename]

positional arguments:
  filename

optional arguments:
  -h, --help  show this help message and exit'''
    t.main()
    out, _ = capsys.readouterr()
    assert out == expected
```

```shell
$ pytest
============================= test session starts ==============================
platform linux -- Python 3.9.0b1, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /tmp/pytest
collected 1 item

test/test_main.py F                                                      [100%]

=================================== FAILURES ===================================
__________________________________ test_main ___________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7f99d29183d0>
tmpdir = local('/tmp/pytest-of-florian/pytest-34/test_main0')

    def test_main(capsys, tmpdir):
        expected = '''\
    usage: t.py [-h] [filename]
    
    positional arguments:
      filename
    
    optional arguments:
      -h, --help  show this help message and exit'''
>       t.main()

test/test_main.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
t.py:14: in main
    contents = sys.stdin.read().encode('utf-8')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.capture.DontReadFromInput object at 0x7f99d2a07820>, args = ()

    def read(self, *args):
>       raise IOError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

.venv/lib/python3.9/site-packages/_pytest/capture.py:732: OSError
=========================== short test summary info ============================
FAILED test/test_main.py::test_main - OSError: pytest: reading from stdin whi...
============================== 1 failed in 0.04s ===============================
```

**Note:** The used approach (`if not sys.stdin.isatty()`) seems to be the recommended way to check whether `stdin` has some data to access. In fact, running and testing the script manually works fine.

- [X] output of `pip list` from the virtual environment you are using

```shell
Package        Version
-------------- -------
attrs          19.3.0
more-itertools 8.3.0
packaging      20.4
pip            20.1.1
pluggy         0.13.1
py             1.8.1
pyparsing      2.4.7
pytest         5.4.2
setuptools     41.2.0
six            1.15.0
wcwidth        0.1.9
```

- [X] pytest and operating system versions

```shell
$ pytest --version
This is pytest version 5.4.2
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

---

Any ideas are welcomed. If I'm missing something, please point me in the right direction. Thanks for making pytest such a great framework!

**Comment by bluetech** [comment]
> Note: The used approach (if not sys.stdin.isatty()) seems to be the recommended way to check whether stdin has some data to access. In fact, running and testing the script manually works fine.

I'm not entirely sure if I understand correctly, but is it possible you got the condition inverted (i.e. you meant to read from stdin if it *is* a TTY)?

**Comment by DahlitzFlorian** [comment]
Thanks for the answer @bluetech!

According to the documentation, `isatty()` returns `True` if a non-console character devices such as NUL[L] (?) is used. So the conditions should be correct. I also linked a SO answer below stating that `isatty()` needs to be used this way to check, whether it is empty or not.

Don't get me wrong, I'm fairly new to this, too, but the way I implemented it (see example above) worked if tested manually. Just writing automated tests for it failed. That's why I opened it to discuss, whether it's a pytest issue or I made a terrible testing mistake.

https://docs.python.org/3/library/sys.html#sys.stdin
https://stackoverflow.com/a/46907341/6707020

**Comment by DahlitzFlorian** [comment]
Found another links: https://stackoverflow.com/a/7576567/6707020
However, I couldn't find the original post from where I have it, but it was similar to the posted StackOverflow answers.

**Comment by bluetech** [comment]
> According to the documentation, isatty() returns True if a non-console character devices such as NUL[L] (?) is used.

It's a bit confusing but it's actually the other way - `isatty` returns true if the file is a terminal/console thingy, and returns false for things like `/dev/null`, pipes and regular files.

**Comment by Zac-HD** [comment]
Hopefully bluetech's answer helped - if not, I think our advice here is "just disable the `capture` plugin if it's incompatible with your usage" :confused:

**Comment by plotski** [comment]
This is an issue and it is not solved.

Testing an application's reaction to input is just as important as testing its output.

The capsys fixture should support this, e.g. `capsys.stdin = "something"`.

@DahlitzFlorian I faced the same issue and wrote a simple capsys replacement.

import io, sys

class MockIO():
    def __init__(self, stdin=''):
        self._stdout = io.StringIO()
        self._stderr = io.StringIO()
        self._stdin = io.StringIO(stdin)

    def __enter__(self):
        sys.stdout = self._stdout
        sys.stderr = self._stderr
        sys.stdin = self._stdin
        return self

    def __exit__(self, _, __, ___):
        sys.stdout = sys.__stdout__
        sys.stderr = sys.__stderr__
        sys.stdin = sys.__stdin__

    @property
    def stdout(self):
        self._stdout.seek(0)
        return self._stdout.read()

    @property
    def stderr(self):
        self._stderr.seek(0)
        return self._stderr.read()

def test_stdin():
    with MockIO(stdin='foo') as cap:
        print('From stdin:', sys.stdin.read())
    assert cap.stdout == 'From stdin: foo\n'
    assert cap.stderr == ''

**Comment by DahlitzFlorian** [comment]
@bluetech if `isatty()` returns `False` for pipes, the implementation I posted is correct (as also shown and suggested by several SO answers). So the issue is still valid and remains a bug IMHO.

@Zac-HD The answer from @bluetech just clarified the usage of `isatty()` and did not show that the usage was wrong. As I already said, the issue is still valid and a reason why an `OSError` occurs is not seen.

@plotski thanks for your reply. Even though your suggestion can help, it is not a proper solution as I still believe this should be fixed in pytest itself.

Hopefully, I find the time to dig deeper into it to find the code causing this issue :pray:

**Comment by plotski** [comment]
> it is not a proper solution as I still believe this should be fixed in pytest itself.

I completely agree. It's a workaround until this issue gets fixed.

**Comment by Zac-HD** [comment]
Thanks for the update - retagged as well as reopened (thanks @DahlitzFlorian :smile:).

**Comment by bluetech** [comment]
pytest's default behavior is to fail with this error "reading from stdin while output is captured!  Consider using `-s`" when trying to read from stdin. This is a good default because if a test tries to read from stdin under regular circumstances it will just get stuck.

Also, pytest capture plugin returns `False` for `isatty`. This also makes sense because it really isn't a tty.

IIUC in this issue two separate feature requests were made:

1. Be able to test a `stdin.isatty() == True` scenario, which doesn't read from stdin otherwise.
2. Be able to test some code which reads from `sys.stdin`.

My first suggestion is: don't do this. Instead of reading from `sys.stdin` directly, change the code to take a `stdin: TextIO` parameter, and only pass `sys.stdin` into that at the very top level (which isn't tested in a direct unit test). Unit tests can then pass arbitrary `StringIO` or anything else they want into that.

If this is not possible, you can mock `sys.stdin` temporarily:

```py
import sys
from unittest import mock

with mock.patch('sys.stdin') as stdin:
    stdin.isatty.return_value = False
    # code under test here
```

Another alternative (better for integration tests for CLI apps) is to run the command in a `subprocess.run` which allows the caller to provide a stdin file.

Finally, if you really want the real `sys.stdin` in the test, you can temporarily disable capturing:

```py
def test_stdin(capfd):
   with capfd.global_and_fixture_disabled():
        # code under test here
```

**Comment by tquangsdh20** [comment]
I have the same issues. I want to test the basic code as below automatically:

```python
def main():
    a = int(input('Enter a:  '))
    return a
```

Some people advice that use:
```python
def test_method(monkeypatch):
    import io
    value = main()
    monkeypatch.setattr('sys.stdin', io.StringIO('2'))
    assert value == 2
```

However, it get the error ```OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.```

-----
Python V3.7.8
pytest 6.2.5

Anybody have the solutions for this test case, please help :( . I would like to test it automatically.

**Comment by RonnyPfannschmidt** [comment]
@tquangsdh20 if you patch after you do the input, it's guaranteed to fail

**Comment by tquangsdh20** [comment]
> 
@RonnyPfannschmidt My bad. It works for me now. Sincerely thanks for your answer and Happy New Year :))

**Comment by RonnyPfannschmidt** [comment]
Same to you and happy testing
